import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

/**
 * Returns a combined class name string from the provided class values.
 * Generated by ShadCN
 *
 * @param inputs - The class values to be combined.
 * @returns The combined class name string.
 */
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

/**
 * Fetches a logo from the given URL and returns it as a base64 encoded string.
 *
 * @param url - The URL of the logo to fetch.
 * @returns A promise that resolves to the base64 encoded string of the logo if the fetch is successful, or null if the fetch fails.
 */
export async function getLogoUsingURL(url: string | null | undefined) {
  if (!url) return null;

  const domain = new URL(url).hostname;

  const response = await fetch(
    `https://icons.duckduckgo.com/ip3/${domain}.ico`
  );

  if (response.ok) {
    const logo = await response.arrayBuffer();
    return Buffer.from(logo).toString("base64");
  }

  return null;
}

/**
 * Parses and stringifies an object to remove any circular references.
 *
 * @param value - The object to parse and stringify.
 * @returns The parsed and stringified object.
 */
export const parseStringify = (value: any) => JSON.parse(JSON.stringify(value));
