import { DialogFooter } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { useFormState } from "react-dom";
import { verifyMFAAction } from "@/lib/api/account";
import Alert from "@/components/common/alert";
import { useEffect } from "react";

import OTP from "@/components/forms/otp";

export default function MFAStepTwo({
  stepper,
}: {
  stepper: (step: number) => void;
}) {
  const initialState = {
    error: "",
    success: false,
  };
  const [state, formAction] = useFormState(verifyMFAAction, initialState);

  // Subscribe to changes in the success field
  useEffect(() => {
    if (state.success) stepper(3);
  }, [state.success]); // Dependency array ensures this runs only when state.success changes

  return (
    <>
      <div className="flex flex-col gap-4">
        <strong className="-mb-2">Verify MFA</strong>
        <p className="text-muted-foreground">
          Please enter the code generated by your MFA device to verify the
          setup.
        </p>
        <form action={formAction}>
          <OTP />
        </form>
        {state.error && <Alert type="error">{state.error}</Alert>}
      </div>
      <DialogFooter className="mt-2">
        <Button variant="ghost" onClick={() => stepper(1)}>
          Go Back
        </Button>
        <Button disabled={!state.success} onClick={() => stepper(3)}>
          Next
        </Button>
      </DialogFooter>
    </>
  );
}
