"use client";

import { useState } from "react";
import MFAFlow from "@/components/auth/sign-in/mfa/mfa-flow";
import Link from "next/link";

export default function MFA() {
  const [isRecovery, setRecovery] = useState(false);

  const handleRecovery = function (e: React.MouseEvent<HTMLAnchorElement>) {
    e.preventDefault();
    setRecovery(true);
  };

  return (
    <div className="mx-auto px-2 grid gap-10 max-w-[360px]">
      <div className="grid gap-2">
        <h2 className="text-4xl font-semibold">Sign In</h2>
        <p className="text-sm text-muted-foreground">
          {isRecovery
            ? "Please use one of the recovery codes to continue."
            : "Please enter the one-time passcode generated by your MFA device."}
        </p>
      </div>

      {isRecovery ? <MFAFlow recovery /> : <MFAFlow />}

      {!isRecovery && (
        <p className="text-sm text-muted-foreground">
          Lost access to the MFA device?
          <Link className="underline ml-1" href="#" onClick={handleRecovery}>
            Recover
          </Link>
        </p>
      )}
    </div>
  );
}
